# ./configs/usgsgaugekrig.yaml

data:
  metadata_file: "/home/exouser/qkrig/data/usgs_site_info.csv"
  data_dir: "/home/exouser/data/usgskrig"
#  site_list_file: "/Users/jmframe/qkrig/data/list_22_camels_basins_NoLeaf.txt"
  site_list_file: "/home/exouser/qkrig/data/usgs_active_sites_Oct01_2024.txt"
  data_cache_directory: "/media/volume/ml_ngen/usgskrig/usgs_retrieval_logs/"
settings:
  date_format: "%Y %m %d"
  add_random_sites: 0
  concurrency: 16
  max_retries: 3
  retry_backoff_seconds: 0.75
  min_area_km2: 0
  bbox: [-125, 24, -66, 50]
plot_config: "/home/exouser/qkrig/configs/plot_config.yaml"
kriging:
  grid_size: 100
  variogram_model: "spherical"
  variogram_bins: 25
  nugget: 1 # Set to 0 for exact interpolation, increase slightly for smoothness
  exact_values: False  # Ensure interpolation matches known points
  nlags: 25  # More lags improve variogram fitting
  weight: False  # Prioritize small distances for better sensitivity
  range: 400  # Variogram range in meters (optional)
  sill: 10