# ./configs/usgsgaugekrig.yaml

data:
  metadata_file: "/Users/jmframe/qkrig/data/usgs_site_info.csv"
  data_dir: "/Users/jmframe/data/usgskrig"
  site_list_file: "/Users/jmframe/qkrig/data/list_22_camels_basins_NoLeaf.txt"

settings:
  date_format: "%Y %m %d"
  add_random_sites: 100

kriging:
  grid_size: 100
  variogram_model: "spherical"
  variogram_bins: 25
  nugget: 1 # Set to 0 for exact interpolation, increase slightly for smoothness
  exact_values: False  # Ensure interpolation matches known points
  nlags: 25  # More lags improve variogram fitting
  weight: False  # Prioritize small distances for better sensitivity
  range: 400  # Variogram range in meters (optional)
  sill: 10